name: Create Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests Pillow pyinstaller

    - name: Create binary with PyInstaller
      run: |
        pyinstaller --onefile --add-data "config:config" --add-data "launchers:launchers" --add-data "sunshine:sunshine" --add-data "utils:utils" lutristosunshine.py

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: lutristosunshine
        path: dist/lutristosunshine

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/lutristosunshine
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          Automated release for commit ${{ github.sha }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
